### PR TITLE
Added bls params

### PR DESCRIPTION
**Pull request by filiplazovic**

### CODE REVIEW

**Comment by drewstone** [comment]
Can you also paste the commands (commented out) that you're running for the Sage program in each file above the ROUND_CONSTS? This will at least allow us to replicate in the future.

We'll need to make sure we also have the parameters set for normal BN254 and not the twisted edwards curve over BN254 as these all will yield different parameters. This is why having the Sage command there is useful when newcomers see the work.

Otherwise, looks great!

**Comment by drewstone** [comment]
I think the README is a good place to put them.

**Comment by filiplazovic** [comment]
Doing the x17 now, bn254 will be handled in separate PR

**Comment by drewstone** [comment]
Sounds good, we should also do for alt-bn128 (or really for that
specifically)

**Comment by filiplazovic** [comment]
I can't find `alt-bn128` here https://github.com/arkworks-rs/curves

**Comment by drewstone** [comment]
It's just ed-on-bn254 @filiplazovic afaik

**Review by drewstone — APPROVED** [review]

**Pull request merged**
